login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('', views.LoginAndRegister.as_view(), name="LoginAndRegister"),
    path("dangxuat/", views.dangxuat, name="dangxuat"),
]

menu/urls.py
from django.urls import path, include
from . import views

app_name = "menu"
urlpatterns = [
    path('', views.showMenu, name="showMenu"),
    path('usermove/', views.userMove.as_view(), name="usermove"),
    path('userfood/', views.userFood.as_view(), name="userfood"),
    path('drivermove/', views.driverMove.as_view(), name="drivermove"),
    path('driverfood/', views.driverFood.as_view(), name="driverfood"),
    path('sellerfood/', views.sellerFood.as_view(), name="sellerfood"),
]

xeomcongnghesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("login.urls")),
    path('menu/', include("menu.urls")),
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.
class QUANAN(models.Model):
    nguoi_dung = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    tenquan = models.CharField(max_length=100, default="Chưa xác định tên quán ăn!")
    vitriquan = models.CharField(max_length=150, null=True)
    lat = models.FloatField(default=0)
    var = models.FloatField(default=0)
    TEN_tinhtrangquan_CHOICES = (
        ('tinhtrang1', 'Mở cửa'),
        ('tinhtrang2', 'Đóng cửa'),
    )
    tinhtrangquan = models.CharField(max_length=255, choices=TEN_tinhtrangquan_CHOICES, default='tinhtrang2')
    def __str__(self):
        return f"{self.tenquan}"

class DOAN(models.Model):
    nguoi_dung = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    quanan = models.ForeignKey(QUANAN, on_delete=models.CASCADE)
    tendoan = models.CharField(max_length=100, default="Chưa xác định tên đồ ăn!")
    giamua = models.IntegerField(default=0)
    TEN_tinhtrangdoan_CHOICES = (
        ('tinhtrang1', 'Còn hàng'),
        ('tinhtrang2', 'Hết hàng'),
    )
    tinhtrangdoan = models.CharField(max_length=255, choices=TEN_tinhtrangdoan_CHOICES, default='tinhtrang1')
    def __str__(self):
        return f"{self.tendoan}"
    
class DONHANGDICHUYEN(models.Model):
    nguoi_dung = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    ten_dang_nhap_tai_xe = models.CharField(max_length=100, null=True)
    vitritaixe = models.CharField(max_length=150, null=True)
    diem_don = models.CharField(max_length=150, null=True)
    diem_den = models.CharField(max_length=150, null=True)
    vitritaixe_lat=models.FloatField(default=0)
    vitritaixe_var=models.FloatField(default=0)
    diem_don_lat=models.FloatField(default=0)
    diem_don_var=models.FloatField(default=0)
    diem_den_lat=models.FloatField(default=0)
    diem_den_var=models.FloatField(default=0)
    giaTien = models.IntegerField(default=0)
    hoaHong = models.FloatField(default=0)
    status = (
        ('tinhtrang1', 'Chờ xác nhận'),
        ('tinhtrang2', 'Đã xác nhận'),
        ('tinhtrang3', 'Đã hủy'),
        ('tinhtrang4', 'Đang di chuyển'),
        ('tinhtrang5', 'Đã hoàn thành'),
    )
    tinhtrang = models.CharField(max_length=255, choices=status, default='tinhtrang1')
    
    def save(self, *args, **kwargs):
        self.hoaHong = float(self.giaTien) * 0.7
        super(DONHANGDICHUYEN, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.nguoi_dung.username}"
    

class GIOHANG(models.Model):
    nguoi_dung = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    doan= models.ForeignKey(DOAN, on_delete=models.CASCADE)
    diem_giao = models.CharField(max_length=150, null=True)
    diem_giao_lat=models.FloatField(default=0)
    diem_giao_var=models.FloatField(default=0)
    ten_dang_nhap_tai_xe = models.CharField(max_length=100, null=True)
    vitritaixe_lat=models.FloatField(default=0)
    vitritaixe_var=models.FloatField(default=0)
    vitritaixe = models.CharField(max_length=150, null=True)
    soluong = models.IntegerField(default=1)
    status = (
        ('tinhtrang1', 'Thêm vào giỏ hàng'),
        ('tinhtrang2', 'Đặt hàng'),
        ('tinhtrang3', 'Đã hủy'),
        ('tinhtrang4', 'Quán ăn xác nhận'),
        ('tinhtrang5', 'Tài xế xác nhận'),
        ('tinhtrang6', 'Quán ăn đang chuẩn bị'),
        ('tinhtrang7', 'Tài xế đang trên đường giao'),
        ('tinhtrang8', 'Đã hoàn thành'),
    )
    tinhtrang = models.CharField(max_length=255, choices=status, default='tinhtrang1')
    ngayMua = models.DateTimeField(default=datetime.now())
    tienship = models.IntegerField(default=0)
    tongTien = models.IntegerField(default=0)
    thanhTien = models.IntegerField(default=0)
    hoaHong = models.FloatField(default=0)

    def save(self, *args, **kwargs):
        self.tongTien = self.soluong * self.doan.giamua
        self.thanhTien = self.soluong * self.doan.giamua + self.tienship
        self.hoaHong = float(self.tienship) * 0.7
        super(GIOHANG, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.nguoi_dung.username} - {self.doan.tendoan} - {self.soluong}"
    

menu/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.decorators import login_required
from login.models import NGUOIDUNG
from django.contrib.auth import logout
from .models import DOAN, QUANAN, DONHANGDICHUYEN, GIOHANG
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.models import Q
# Create your views here. 
@login_required(login_url='') 
def showMenu(request):
    current_user = request.user
    nguoidung = NGUOIDUNG.objects.filter(TEN_DANG_NHAP=current_user.username).first()
    user_role = nguoidung.QUYEN
    context = {
            'username': nguoidung.TEN_DANG_NHAP,
            'fullname': nguoidung.HO_TEN,
            'email': nguoidung.EMAIL,
            'phonenumber': nguoidung.SO_DIEN_THOAI,
            'user_role': user_role
        }

    return render(request, "menu/menu.html", context)
    
class sellerFood(LoginRequiredMixin, View):
    login_url = '/login/'

    def get_context_data(self, request):
        current_user = request.user
        nguoidung = NGUOIDUNG.objects.filter(TEN_DANG_NHAP=current_user.username).first()
        user_role = nguoidung.QUYEN
        nguoi_dung = request.user
        doan_list = DOAN.objects.filter(nguoi_dung=nguoi_dung)
        quanan = QUANAN.objects.filter(nguoi_dung=nguoi_dung).first()
        quanan_id = quanan.id
        quanan_lat = quanan.lat
        quanan_var = quanan.var
        tenquan = quanan.tenquan
        tinhtrangquan = quanan.tinhtrangquan
        danhsachdonhang = GIOHANG.objects.filter( doan__quanan__id = quanan_id ).filter(
                Q(tinhtrang='tinhtrang2') | Q(tinhtrang='tinhtrang4') | Q(tinhtrang='tinhtrang5') | Q(tinhtrang='tinhtrang6') | Q(tinhtrang='tinhtrang7') | Q(tinhtrang='tinhtrang8')
            )
        danhsachdonhangdangthuchien = GIOHANG.objects.filter( doan__quanan__id = quanan_id ).filter(
                Q(tinhtrang='tinhtrang2') | Q(tinhtrang='tinhtrang4') | Q(tinhtrang='tinhtrang5') | Q(tinhtrang='tinhtrang6')
            )
        
        context = {
            'username': nguoidung.TEN_DANG_NHAP,
            'fullname': nguoidung.HO_TEN,
            'email': nguoidung.EMAIL,
            'phonenumber': nguoidung.SO_DIEN_THOAI,
            'user_role': user_role,
            "doan_list": doan_list,
            "tenquan": tenquan,
            "tinhtrangquan": tinhtrangquan,
            "quanan_id": quanan_id,
            "quanan_lat": quanan_lat,
            "quanan_var": quanan_var,
            'danhsachdonhang':danhsachdonhang,
            'danhsachdonhangdangthuchien': danhsachdonhangdangthuchien
        }
        return context

    def get(self, request):
        context = self.get_context_data(request)
        return render(request, "menu/sellerfood.html", context)
    
    def post(self, request):
        if request.method == 'POST':
            if 'action' in request.POST:
                action = request.POST.get('action')
                if action == 'addfood':
                    tendoan = request.POST.get('tendoan')
                    giamua = request.POST.get('giamua')
                    tinhtrangdoan = request.POST.get('tinhtrangdoan')
                    current_user = request.user
                    quanan = QUANAN.objects.filter(nguoi_dung=current_user).first()
                    doan = DOAN(nguoi_dung=current_user, quanan=quanan, tendoan=tendoan, giamua=giamua, tinhtrangdoan=tinhtrangdoan)
                    doan.save()
                    message_addfood = "Thêm đồ ăn thành công"
                    context = self.get_context_data(request)
                    context['message_addfood'] = message_addfood
                    return render(request, 'menu/sellerfood.html', context)
                
                elif action == 'quanan':
                    quanan_id = request.POST.get('quanan_id')
                    quanan = QUANAN.objects.get(id=quanan_id)
                    tenquan = request.POST.get('tenquan')
                    tinhtrangquanan = request.POST.get('tinhtrangquanan')
                    quanan.tenquan = tenquan
                    quanan.tinhtrangquan = tinhtrangquanan
                    quanan.save()
                    message_quanan = "Sửa thông tin thành công"
                    context = self.get_context_data(request)
                    context['message_quanan'] = message_quanan
                    return render(request, 'menu/sellerfood.html', context)
                    
                elif action == 'suafood':
                    doan_id = request.POST.get('doan_id')
                    doan = DOAN.objects.get(id=doan_id)
                    tendoan = request.POST.get('tendoan')
                    giamua = request.POST.get('giamua')
                    tinhtrangdoan = request.POST.get('tinhtrangdoan')
                    doan.tendoan = tendoan
                    doan.giamua = giamua
                    doan.tinhtrangdoan = tinhtrangdoan
                    doan.save()
                    context = self.get_context_data(request)
                    return render(request, 'menu/sellerfood.html', context)
                
                elif action == 'setAddress':
                    diachifull = request.POST.get('pickup_location')
                    diachi = request.POST.get('pickup_location_hide')
                    pickup = diachi.split(',')
                    quanan_id = request.POST.get('quanan_id')
                    quanan = QUANAN.objects.get(id=quanan_id)
                    quanan.lat = float(pickup[0])
                    quanan.var = float(pickup[1])
                    quanan.vitriquan = diachifull
                    quanan.save()
                    message_suaDiaChi = "Sửa địa chỉ thành công"
                    context = self.get_context_data(request)
                    context['message_suaDiaChi'] = message_suaDiaChi
                    return render(request, 'menu/sellerfood.html', context)
                
                elif action == 'deletefood':
                    doan_id = request.POST.get('doan_id')
                    try:
                        doan = DOAN.objects.get(id=doan_id)
                        doan.delete()
                        return JsonResponse({'success': True})
                    except DOAN.DoesNotExist:
                        return JsonResponse({'success': False, 'error': 'Đồ ăn không tồn tại'})
                elif action == 'xacNhanDonHang':
                    giohangid = request.POST.get('giohangid')
                    giohang = GIOHANG.objects.filter(id=giohangid).first()
                    if giohang.tinhtrang == 'tinhtrang2':
                        giohang.tinhtrang = 'tinhtrang4'
                        giohang.save()
                    context = self.get_context_data(request)
                    context['messageXacNhan'] = "Xác nhận món ăn thành công!"
                    return render(request, 'menu/sellerfood.html', context) 
                elif action == 'xacNhanChuanBi':
                    giohangid = request.POST.get('giohangid')
                    giohang = GIOHANG.objects.filter(id=giohangid).first()
                    if giohang.tinhtrang == 'tinhtrang5':
                        giohang.tinhtrang = 'tinhtrang6'
                        giohang.save()
                    context = self.get_context_data(request)
                    context['messageXacNhan'] = "Xác nhận chuẩn bị món ăn thành công! Hãy chuẩn bị món ăn"
                    return render(request, 'menu/sellerfood.html', context) 
        
        return render(request, 'menu/sellerfood.html')

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
class userMove(LoginRequiredMixin, View):
    login_url = '/login/'
    def get_context_data(self, request):
        current_user = request.user
        nguoidung = NGUOIDUNG.objects.filter(TEN_DANG_NHAP=current_user.username).first()
        user_role = nguoidung.QUYEN
        nguoi_dung = request.user
        donhangdichuyen_list = DONHANGDICHUYEN.objects.filter(nguoi_dung=nguoi_dung)
        donhanghientai = DONHANGDICHUYEN.objects.filter(
            nguoi_dung=nguoi_dung
            ).filter(
                Q(tinhtrang='tinhtrang1') | Q(tinhtrang='tinhtrang2') | Q(tinhtrang='tinhtrang4')
            )
        context = {
                'username': nguoidung.TEN_DANG_NHAP,
                'fullname': nguoidung.HO_TEN,
                'email': nguoidung.EMAIL,
                'phonenumber': nguoidung.SO_DIEN_THOAI,
                'user_role': user_role, 
                'donhangdichuyen_list': donhangdichuyen_list,
                'donhanghientai': donhanghientai
        }
        return context
    
    def get(self, request):
        context = self.get_context_data(request)
        return render(request, "menu/usermove.html", context)
    
    def post(self, request):
        if request.method == 'POST':
            if 'action' in request.POST:
                action = request.POST.get('action')
                if action == 'datXe':
                    current_user = request.user
                    donhangcuaban = DONHANGDICHUYEN.objects.filter(nguoi_dung=current_user)
                    for donhang in donhangcuaban:
                        if donhang.tinhtrang == 'tinhtrang1' or donhang.tinhtrang == 'tinhtrang2' or donhang.tinhtrang == 'tinhtrang4':
                            context = self.get_context_data(request)
                            return render(request, "menu/usermove.html", context)
                    diemDon = request.POST.get('pickup_location')
                    diemDen = request.POST.get('destination_location')
                    diachiDon = request.POST.get('pickup_location_hide')
                    pickupDon = diachiDon.split(',')

menu/templates/menu/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'menu/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'menu/fonts/themify-icons-font/themify-icons/themify-icons.css' %}">  
</head>
<body>
    <div id="main">
        <div id="header">
            <ul class="menu">
                <li>
                    <i class="ti-menu" onclick="toggleSubMenu()"></i>
                    <p>Menu</p>
                </li>
            </ul>
            <a href="#"><img class="logo" src="{% static 'menu/img/logo/logograb.png' %}" alt="logograb"></a>
            <div class="info">
                    <ul>
                        <li><a href="#" onclick="openModalInfo()">Thông tin</a></li>
                        <li><a href="{% url 'login:dangxuat' %}">Đăng xuất</a></li>
                    </ul>
                </i>
            </div>
        </div>
        
        <div class="submenu" style="display: none;">
            <ul class="object">
                <li>Người dùng</li>
                <li>Tài xế</li>
                <li>Thương nhân</li>
            </ul>
            <div id="choose-user" class="choose">
                <div>
                    <li><a href="{% url 'menu:usermove' %}">Di chuyển</a></li>
                    <p>Tất tần tật về các dịch vụ phục vụ nhu cầu đi lại của bạn</p>
                </div>
                <div>
                    <li><a href="{% url 'menu:userfood' %}">GrabFood</a></li>
                    <p>Thưởng thức món ngon ngay tại nhà</p>
                </div>
                <div>
                    <li><a href="#">GrabExpress</a></li>
                    <p>Dịch vụ giao hàng nhanh chóng và tiện lợi</p>
                </div>
            </div>
            <div id="choose-driver" class="choose" style="display: none;">
                <div>
                    <li><a href="{% url 'menu:drivermove' %}">Di chuyển</a></li>
                    <p>Làm chủ tài chính và thời gian.</p>
                </div>
                <div>
                    <li><a href="{% url 'menu:driverfood' %}">GrabFood</a></li>
                    <p>Kiếm thêm thu nhập với dịch vụ giao thức ăn.</p>
                </div>
                <div>
                    <li><a href="#">GrabExpress</a></li>
                    <p>Kiếm nhiều hơn nữa với dịch vụ giao hàng.</p>
                </div>
            </div>
            <div id="choose-vendor" class="choose" style="display: none;">
                <div>
                    <li><a href="{% url 'menu:sellerfood' %}">GrabFood</a></li>
                    <p>Tăng doanh thu khi mở quán ăn trên Grab và tiếp cận hàng triệu người dùng</p>
                </div>
                <div>
                    <li><a href="#">GrabMart</a></li>
                    <p>Phát triển doanh nghiệp của bạn bằng cách đưa hàng hóa đến tận tay người tiêu dùng</p>
                </div>
            </div>
        </div>        

        <div id="content">
            <div class="slider">
                <video autoplay loop class="video">
                    <source src="{% static 'menu/video/slide-video.webm' %}" type="video/webm">
                    Your browser does not support the video tag.
                </video>
            </div>

            <div class="introduce">
                <div class="title">
                    <h2>Từ những dịch vụ thiết yếu đến cơ hội gia tăng thu nhập. Tất cả đều có trên một nền tảng</h2>
                </div>

                <div class="menu">
                    <ul>
                        <li class="selected"><a href="javascript:void(0)" onclick="selectMenuItem(this)">Người tiêu dùng</a></li>
                        <li><a href="javascript:void(0)" onclick="selectMenuItem(this)">Đối tác tài xế</a></li>
                        <li><a href="javascript:void(0)" onclick="selectMenuItem(this)">Đối tác thương nhân</a></li>
                    </ul>
                </div>
                
                <div id="user" style="display: block;">
                    <div class="select">
                        <div>
                            <h2>Giao hàng</h2>
                        </div>
                        <div>
                            <ul>
                                <li>
                                    <h3>Đồ ăn</h3>
                                    <p>Giao món tận tay</p>
                                </li>
                                <li>
                                    <h3>Đi chợ</h3>
                                    <p>Tìm kiếm mọi thứ bạn cần, hàng tạp hóa và hơn thế nữa</p>
                                </li>
                                <li>
                                    <h3>Giao hàng</h3>
                                    <p>Giao hàng, gói kiện và hơn thế nữa</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="select">
                        <div>
                            <h2>Di chuyển</h2>
                        </div>
                        <div>
                            <ul>
                                <li>
                                    <h3>Di chuyển</h3>
                                    <p>Chọn phương tiện di chuyển phù hợp, đi đến nơi về đến chốn an toàn</p>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="select">
                        <div>
                            <h2>Dịch vụ tài chính</h2>
                        </div>
                        <div>
                            <ul>
                                <li>
                                    <h3>Thanh toán</h3>
                                    <p>Thanh toán không tiền mặt bảo mật và liền mạch, dù là trực tuyến hay tại cửa hàng</p>
                                </li>
                                <li>
                                    <h3>Hóa đơn</h3>
                                    <p>Thanh toán đơn dễ dàng, tiện lợi</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div id="driver" style="display: none;">
                    <div class="select">
                        <div>
                            <h2>Tăng cơ hội thu nhập</h2>
                        </div>
                        <div>
                            <ul>
                                <li>
                                    <h3>Trở thành đối tác tài xế</h3>
                                    <p>Làm chủ thời gian của mình</p>
                                </li>
                                <li>
                                    <h3>Trở thành đối tác giao hàng</h3>
                                    <p>Giao hàng và tăng cơ hội thu nhập</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                
                <div id="vendor" style="display: none;">
                    <div class="select">
                        <div>
                            <h2>Phát triển doanh nghiệp của bạn</h2>
                        </div>
                        <div>
                            <ul>
                                <li>
                                    <h3>Bán hàng trên Grab</h3>
                                    <p>Trở thành đối tác của Grab để tiếp cận được nhiều khách hàng hơn.</p>
                                </li>
                                <li>
                                    <h3>Thanh toán không tiền mặt</h3>
                                    <p>Giao dịch dễ dàng và an toàn với phương thức thanh toán không tiền mặt.</p>
                                </li>
                                <li>
                                    <h3>Giao hàng với chúng tôi</h3>
                                    <p>Giao mọi đơn đặt hàng đến khách hàng của bạn một cách thuận tiện.</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="modal-info" style="display: none;">
        <div class="modal-container">
            <div class="modal-close" onclick="closeModalInfo()">
                <i class="ti-close"></i>
            </div>
    
            <header class="modal-header">
                <h1>Thông tin</h1>
            </header>
    
            <div class="modal-body">
                <label for="" class="modal-label">Tên đăng nhập</label>
                <input type="text" class="modal-input" name="username" value="{{ username }}" readonly>
                <label for="" class="modal-label">Họ và tên</label>
                <input type="text" class="modal-input" name="fullname" value="{{ fullname }}" readonly>
                <label for="" class="modal-label">Email</label>
                <input type="email" class="modal-input" name="email" value="{{ email }}" readonly>
                <label for="" class="modal-label">Số điện thoại</label>
                <input type="text" class="modal-input" name="phonenumber" value="{{ phonenumber }}" readonly>
                <label for="role" class="modal-label">Quyền</label>
                <input type="text" class="modal-input" name="role" value="{{ user_role }}" readonly>
            </div>
        </div>
    </div>    

    <script>
        function openModalInfo() {
            document.getElementById("modal-info").style.display = "flex";
        }

        function closeModalInfo() {
            document.getElementById("modal-info").style.display = "none";
        }

        document.addEventListener('click', function(event) {
            var submenu = document.querySelector('.submenu');
            var menuIcon = document.querySelector('.ti-menu');
            var isClickInsideMenu = menuIcon.contains(event.target);
            var isClickInsideSubmenu = submenu.contains(event.target);

            if (!isClickInsideMenu && !isClickInsideSubmenu) {
                submenu.style.display = 'none';
            }
        });

        function toggleSubMenu() {
            var submenu = document.querySelector('.submenu');
            submenu.style.display = submenu.style.display === 'none' ? 'flex' : 'none';
        }

        document.addEventListener('DOMContentLoaded', function() {
            var role = "{{ user_role }}"; 
        
            document.querySelectorAll('.choose').forEach(function(submenu) {
                submenu.style.display = 'none';
            });
        
            document.querySelectorAll('.object li').forEach(function(item) {
                item.style.display = 'none';
            });
        
            switch (role) {
                case 'user':
                    document.getElementById('choose-user').style.display = 'block';
                    document.querySelector('.object li:nth-child(1)').style.display = 'block'; 
                    break;
                case 'driver':
                    document.getElementById('choose-driver').style.display = 'block';
                    document.querySelector('.object li:nth-child(2)').style.display = 'block'; 
                    break;
                case 'seller':
                    document.getElementById('choose-vendor').style.display = 'block';
                    document.querySelector('.object li:nth-child(3)').style.display = 'block';
                    break;
                default:
                    break;
            }
        });        
        
        function selectMenuItem(element) {
            var menuItems = document.querySelectorAll('#content .menu li');
            menuItems.forEach(function(item) {
                item.classList.remove('selected');
            });
            element.parentNode.classList.add('selected');
            var menuItem = element.textContent.trim(); 
            switch (menuItem) {
                case 'Người tiêu dùng':
                    showMenuUser();
                    break;
                case 'Đối tác tài xế':
                    showMenuDriver();
                    break;
                case 'Đối tác thương nhân':
                    showMenuVendor();
                    break;
                case 'Doanh nghiệp':
                    showMenuBussiness();
                    break;
                default:
                    break;
            }
        }

        function showMenuUser() {
            document.getElementById("user").style.display = "block";
            document.getElementById("driver").style.display = "none";
            document.getElementById("vendor").style.display = "none";
            document.getElementById("bussiness").style.display = "none";
        }

        function showMenuDriver() {
            document.getElementById("user").style.display = "none";
            document.getElementById("driver").style.display = "block";
            document.getElementById("vendor").style.display = "none";
            document.getElementById("bussiness").style.display = "none";
        }

        function showMenuVendor() {
            document.getElementById("user").style.display = "none";
            document.getElementById("driver").style.display = "none";
            document.getElementById("vendor").style.display = "block";
            document.getElementById("bussiness").style.display = "none";
        }
    </script>
</body>
</html>